import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
    index("features/main/pages/home-page.tsx"),
    route(
        "/login",
        "features/auth/pages/login.tsx"
    ),
    route(
        "/forgot-password",
        "features/auth/pages/forgot-password.tsx"
    ),
    route(
        "/register",
        "features/auth/pages/register.tsx"
    ),
    route(
        "/registration-success",
        "features/auth/pages/registration-success.tsx"
    ),
    route(
        "/reset-password",
        "features/auth/pages/reset-password.tsx"
    ),
    route(
        "/stories/:storyId",
        "features/chapters/pages/chapters.tsx"
    ),
    route(
        "/stories/:storyId/:chapterId",
        "features/contents/pages/content.tsx"
    ),
    route(
        "/stories/:storyId/:chapterId/quiz",
        "features/contents/pages/quiz.tsx"
    ),
    route(
        "/stories/:storyId/:chapterId/recording",
        "features/contents/pages/recording.tsx"
    ),
    route(
        "/stories/:storyId/:chapterId/complete",
        "features/contents/pages/complete.tsx"
    ),
    route(
        "/blog",
        "features/stories/pages/blog.tsx"
    ),
    route(
        "/grammer",
        "features/stories/pages/grammer.tsx"
    )
] satisfies RouteConfig;
