// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/verification": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/registration-success": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/stories": {
    params: {};
  };
  "/stories/:storyId/chapters": {
    params: {
      "storyId": string;
    };
  };
  "/stories/:storyId/:chapterId": {
    params: {
      "storyId": string;
      "chapterId": string;
    };
  };
  "/stories/:storyId/:chapterId/quiz": {
    params: {
      "storyId": string;
      "chapterId": string;
    };
  };
  "/stories/:storyId/:chapterId/recording": {
    params: {
      "storyId": string;
      "chapterId": string;
    };
  };
  "/stories/:storyId/:chapterId/complete": {
    params: {
      "storyId": string;
      "chapterId": string;
    };
  };
  "/blog": {
    params: {};
  };
  "/grammer": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/forgot-password" | "/verification" | "/register" | "/registration-success" | "/reset-password" | "/stories" | "/stories/:storyId/chapters" | "/stories/:storyId/:chapterId" | "/stories/:storyId/:chapterId/quiz" | "/stories/:storyId/:chapterId/recording" | "/stories/:storyId/:chapterId/complete" | "/blog" | "/grammer";
  };
  "features/main/pages/home-page.tsx": {
    id: "features/main/pages/home-page";
    page: "/";
  };
  "features/auth/pages/login.tsx": {
    id: "features/auth/pages/login";
    page: "/login";
  };
  "features/auth/pages/forgot-password.tsx": {
    id: "features/auth/pages/forgot-password";
    page: "/forgot-password";
  };
  "features/auth/pages/verification.tsx": {
    id: "features/auth/pages/verification";
    page: "/verification";
  };
  "features/auth/pages/register.tsx": {
    id: "features/auth/pages/register";
    page: "/register";
  };
  "features/auth/pages/registration-success.tsx": {
    id: "features/auth/pages/registration-success";
    page: "/registration-success";
  };
  "features/auth/pages/reset-password.tsx": {
    id: "features/auth/pages/reset-password";
    page: "/reset-password";
  };
  "features/learning/pages/stories.tsx": {
    id: "features/learning/pages/stories";
    page: "/stories";
  };
  "features/learning/pages/chapters.tsx": {
    id: "features/learning/pages/chapters";
    page: "/stories/:storyId/chapters";
  };
  "features/learning/contents/pages/content.tsx": {
    id: "features/learning/contents/pages/content";
    page: "/stories/:storyId/:chapterId";
  };
  "features/learning/contents/pages/quiz.tsx": {
    id: "features/learning/contents/pages/quiz";
    page: "/stories/:storyId/:chapterId/quiz";
  };
  "features/learning/contents/pages/recording.tsx": {
    id: "features/learning/contents/pages/recording";
    page: "/stories/:storyId/:chapterId/recording";
  };
  "features/learning/contents/pages/complete.tsx": {
    id: "features/learning/contents/pages/complete";
    page: "/stories/:storyId/:chapterId/complete";
  };
  "features/learning/stories/pages/blog.tsx": {
    id: "features/learning/stories/pages/blog";
    page: "/blog";
  };
  "features/learning/stories/pages/grammer.tsx": {
    id: "features/learning/stories/pages/grammer";
    page: "/grammer";
  };
};