// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/verification": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/registration-success": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/stories": {
    params: {};
  };
  "/stories/:storyId/chapters": {
    params: {
      "storyId": string;
    };
  };
  "/stories/:storyId/chapters/:chapterId": {
    params: {
      "storyId": string;
      "chapterId": string;
    };
  };
  "/stories/:storyId/chapters/:chapterId/sentence-arrangement": {
    params: {
      "storyId": string;
      "chapterId": string;
    };
  };
  "/stories/:storyId/chapters/:chapterId/speaking-practice": {
    params: {
      "storyId": string;
      "chapterId": string;
    };
  };
  "/stories/:storyId/chapters/:chapterId/completion": {
    params: {
      "storyId": string;
      "chapterId": string;
    };
  };
  "/blog": {
    params: {};
  };
  "/grammer": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/forgot-password" | "/verification" | "/register" | "/registration-success" | "/reset-password" | "/stories" | "/stories/:storyId/chapters" | "/stories/:storyId/chapters/:chapterId" | "/stories/:storyId/chapters/:chapterId/sentence-arrangement" | "/stories/:storyId/chapters/:chapterId/speaking-practice" | "/stories/:storyId/chapters/:chapterId/completion" | "/blog" | "/grammer";
  };
  "features/main/pages/main.tsx": {
    id: "features/main/pages/main";
    page: "/";
  };
  "features/auth/pages/login.tsx": {
    id: "features/auth/pages/login";
    page: "/login";
  };
  "features/auth/pages/forgot-password.tsx": {
    id: "features/auth/pages/forgot-password";
    page: "/forgot-password";
  };
  "features/auth/pages/verification.tsx": {
    id: "features/auth/pages/verification";
    page: "/verification";
  };
  "features/auth/pages/register.tsx": {
    id: "features/auth/pages/register";
    page: "/register";
  };
  "features/auth/pages/registration-success.tsx": {
    id: "features/auth/pages/registration-success";
    page: "/registration-success";
  };
  "features/auth/pages/reset-password.tsx": {
    id: "features/auth/pages/reset-password";
    page: "/reset-password";
  };
  "features/learning/pages/stories.tsx": {
    id: "features/learning/pages/stories";
    page: "/stories";
  };
  "features/learning/pages/chapters.tsx": {
    id: "features/learning/pages/chapters";
    page: "/stories/:storyId/chapters";
  };
  "features/learning/pages/chapter-detail.tsx": {
    id: "features/learning/pages/chapter-detail";
    page: "/stories/:storyId/chapters/:chapterId";
  };
  "features/learning/pages/sentence-arrangement.tsx": {
    id: "features/learning/pages/sentence-arrangement";
    page: "/stories/:storyId/chapters/:chapterId/sentence-arrangement";
  };
  "features/learning/pages/speaking-practice.tsx": {
    id: "features/learning/pages/speaking-practice";
    page: "/stories/:storyId/chapters/:chapterId/speaking-practice";
  };
  "features/learning/pages/course-completion.tsx": {
    id: "features/learning/pages/course-completion";
    page: "/stories/:storyId/chapters/:chapterId/completion";
  };
  "features/learning/stories/pages/blog.tsx": {
    id: "features/learning/stories/pages/blog";
    page: "/blog";
  };
  "features/learning/stories/pages/grammer.tsx": {
    id: "features/learning/stories/pages/grammer";
    page: "/grammer";
  };
};